--AGREGANDO LLAVES FORANEAS
ALTER TABLE DETALLE_CONTRATO_ALQUILER
ADD FOREIGN KEY (COD_CON) REFERENCES CONTRATOALQUILER
ALTER TABLE DETALLE_CONTRATO_ALQUILER
ADD FOREIGN KEY(IDE_EQU) REFERENCES EQUIPO
ALTER TABLE DETALLE_CONTRATO_MANTENIMIENTO
ADD FOREIGN KEY (COD_CON) REFERENCES CONTRATOMANTENIMIENTO
ALTER TABLE DETALLE_FICHA_DAÑO
ADD FOREIGN KEY (COD_FIC) REFERENCES FICHADEDAÑOS
ALTER TABLE DETALLE_FICHA_RECLAMO
ADD FOREIGN KEY (COD_FIC) REFERENCES FICHARECLAMO
ALTER TABLE CONTRATOALQUILER
ADD FOREIGN KEY (IDE_CLI) REFERENCES CLIENTE
ALTER TABLE CONTRATOALQUILER
ADD FOREIGN KEY (IDE_CON) REFERENCES CONTRATISTA
ALTER TABLE CONTRATOMANTENIMIENTO
ADD FOREIGN KEY(IDE_CLI) REFERENCES CLIENTE
ALTER TABLE CONTRATOMANTENIMIENTO
ADD FOREIGN KEY(IDE_CON) REFERENCES CONTRATISTA
ALTER TABLE DETALLE_CONTRATO_MANTENIMIENTO
ADD FOREIGN KEY(COD_EQU_MAN) REFERENCES TIPOMANTENIMIENTO
ALTER TABLE FICHADEDAÑOS
ADD FOREIGN KEY(IDE_CLI) REFERENCES CLIENTE
ALTER TABLE FICHADEDAÑOS
ADD FOREIGN KEY(IDE_CON) REFERENCES CONTRATISTA
ALTER TABLE FICHARECLAMO
ADD FOREIGN KEY(IDE_CLI) REFERENCES CLIENTE
ALTER TABLE FICHARECLAMO
ADD FOREIGN KEY(IDE_CON) REFERENCES CONTRATISTA
ALTER TABLE DETALLE_CONTRATO_MANTENIMIENTO
ADD FOREIGN KEY(IDE_EQU) REFERENCES EQUIPO
ALTER TABLE DETALLE_FICHA_DAÑO
ADD FOREIGN KEY(IDE_EQU) REFERENCES EQUIPO
ALTER TABLE DETALLE_FICHA_DAÑO
ADD FOREIGN KEY (COD_TIP_DAÑ) REFERENCES TIPO_DAÑO
ALTER TABLE DETALLE_FICHA_RECLAMO
ADD FOREIGN KEY(IDE_EQU) REFERENCES EQUIPO
ALTER TABLE DETALLE_FICHA_RECLAMO
ADD FOREIGN KEY (COD_TIP_REC) REFERENCES TIPO_RECLAMO
ALTER TABLE EQUIPO
ADD FOREIGN KEY(COD_TIP_EQU) REFERENCES TIPO_EQUIPO
ALTER TABLE EQUIPO
ADD FOREIGN KEY (COD_EST) REFERENCES ESTADO_EQUIPO
ALTER TABLE FICHA_DEVOLUCION
ADD FOREIGN KEY (IDE_EQU) REFERENCES EQUIPO
ALTER TABLE FICHA_DEVOLUCION
ADD FOREIGN KEY (IDE_CLI) REFERENCES CLIENTE
ALTER TABLE FICHA_DEVOLUCION
ADD FOREIGN KEY (IDE_CON) REFERENCES CONTRATISTA